name: covid_app
description: App used to see the trend of CoronaVirus
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  get_it: ^4.0.1
  flutter_bloc:
  bloc:
  equatable: ^1.1.1
  connectivity: ^0.4.8+2
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+3
  # Database
  moor_flutter: ^2.1.1
  provider: ^4.0.5
  intl:
  data_connection_checker: ^0.3.4
  liquid_swipe: ^1.4.3
  google_fonts:
  fl_animated_linechart:
  pull_to_refresh:
  url_launcher:
  package_info:
  # charts_flutter:
  charts_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.4.0

  mockito: ^4.1.1

  flutter_launcher_icons:

  build_runner:

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/app_icon_2.png"

flutter:
  # the material Icons class.
  uses-material-design: true

