name: covid_app
description: App used to see the trend of CoronaVirus
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  get_it: ^2.0.1

  flutter_bloc:
  
  bloc: 

  equatable: ^1.1.1

  connectivity: ^0.4.3+7

  http: ^0.12.0+2

  shared_preferences: ^0.5.3+4
  # Database
  moor_flutter: ^2.1.0

  provider: ^4.0.4
  intl:

  data_connection_checker: ^0.3.4

  liquid_swipe: ^1.4.2

  google_fonts:

  fl_animated_linechart:

  pull_to_refresh:

  url_launcher: 
  
  package_info:

  # fl_chart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.1.0

  mockito: ^4.1.0

  flutter_launcher_icons:

  build_runner:

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  # the material Icons class.
  uses-material-design: true

