name: covid_app
description: App used to see the trend of CoronaVirus
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  get_it: ^2.0.1

  flutter_bloc: ^0.21.0

  equatable: ^0.4.0

  connectivity: ^0.4.3+7

  http: ^0.12.0+2

  shared_preferences: ^0.5.3+4
  # Database
  moor_flutter: ^2.1.0

  provider: ^3.0.0+1

  data_connection_checker: ^0.3.4
  fl_chart: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.1.0
  mockito: ^4.1.0
  build_runner:
    
flutter:
  # the material Icons class.
  uses-material-design: true

